//import { Geist, Geist_Mono, Inspiration } from "next/font/google";
import "./globals.css";
import NavForm from "@/components/navForm";
import FooterForm from "@/components/footerForm";
/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

export const metadata = {
  title: "Reve",
  description: "Generated by @Aiden-Kwak",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavForm/>
        {children}
        <FooterForm/>
        <div className="fixed-buttons">
          <a
            href="https://pf.kakao.com/_xfLgZn"
            target="_blank"
            rel="noopener noreferrer"
            className="fixed-button button-1"
          >
            <img src="/icon/kakao-talk.png" alt="채널 1" />
          </a>
          <a
            href="https://www.instagram.com/reve.class"
            target="_blank"
            rel="noopener noreferrer"
            className="fixed-button button-2"
          >
            <img src="/icon/instagram.png" alt="채널 1" />
          </a>
        </div>
      </body>
    </html>
  );
}
